// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenderTask.DataAccess.Context;

#nullable disable

namespace TenderTask.DataAccess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617185924_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TenderTask.DataAccess.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Oil & Gas"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Medical Services"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Construction"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "IT Services"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Consulting"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Manufacturing"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Education"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Translation Services"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Maintenance"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Logistics"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Financial Services"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Security"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Environmental Services"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Design"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Agriculture"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Telecommunications"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Food & Beverage"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Transport"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Real Estate"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Legal Services"
                        });
                });

            modelBuilder.Entity("TenderTask.DataAccess.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "Oil Co. 1"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyName = "Oil Co. 2"
                        },
                        new
                        {
                            CompanyId = 3,
                            CompanyName = "Oil Co. 3"
                        },
                        new
                        {
                            CompanyId = 4,
                            CompanyName = "Oil Co. 4"
                        },
                        new
                        {
                            CompanyId = 5,
                            CompanyName = "Medical Co. 1"
                        },
                        new
                        {
                            CompanyId = 6,
                            CompanyName = "Medical Co. 2"
                        },
                        new
                        {
                            CompanyId = 7,
                            CompanyName = "Medical Co. 3"
                        },
                        new
                        {
                            CompanyId = 8,
                            CompanyName = "Construction Co. 1"
                        },
                        new
                        {
                            CompanyId = 9,
                            CompanyName = "Construction Co. 2"
                        },
                        new
                        {
                            CompanyId = 10,
                            CompanyName = "Construction Co. 3"
                        },
                        new
                        {
                            CompanyId = 11,
                            CompanyName = "IT Co. 1"
                        },
                        new
                        {
                            CompanyId = 12,
                            CompanyName = "IT Co. 2"
                        },
                        new
                        {
                            CompanyId = 13,
                            CompanyName = "Consulting Co. 1"
                        },
                        new
                        {
                            CompanyId = 14,
                            CompanyName = "Consulting Co. 2"
                        },
                        new
                        {
                            CompanyId = 15,
                            CompanyName = "Consulting Co. 3"
                        },
                        new
                        {
                            CompanyId = 16,
                            CompanyName = "Manufacturing Co. 1"
                        },
                        new
                        {
                            CompanyId = 17,
                            CompanyName = "Manufacturing Co. 2"
                        },
                        new
                        {
                            CompanyId = 18,
                            CompanyName = "Manufacturing Co. 3"
                        },
                        new
                        {
                            CompanyId = 19,
                            CompanyName = "Education Co. 1"
                        },
                        new
                        {
                            CompanyId = 20,
                            CompanyName = "Education Co. 2"
                        },
                        new
                        {
                            CompanyId = 21,
                            CompanyName = "Translation Co. 1"
                        },
                        new
                        {
                            CompanyId = 22,
                            CompanyName = "Translation Co. 2"
                        },
                        new
                        {
                            CompanyId = 23,
                            CompanyName = "Translation Co. 3"
                        },
                        new
                        {
                            CompanyId = 24,
                            CompanyName = "Maintenance Co. 1"
                        },
                        new
                        {
                            CompanyId = 25,
                            CompanyName = "Maintenance Co. 2"
                        },
                        new
                        {
                            CompanyId = 26,
                            CompanyName = "Logistics Co. 1"
                        },
                        new
                        {
                            CompanyId = 27,
                            CompanyName = "Logistics Co. 2"
                        },
                        new
                        {
                            CompanyId = 28,
                            CompanyName = "Logistics Co. 3"
                        },
                        new
                        {
                            CompanyId = 29,
                            CompanyName = "Logistics Co. 4"
                        },
                        new
                        {
                            CompanyId = 30,
                            CompanyName = "Financial Co. 1"
                        },
                        new
                        {
                            CompanyId = 31,
                            CompanyName = "Financial Co. 2"
                        },
                        new
                        {
                            CompanyId = 32,
                            CompanyName = "Financial Co. 3"
                        },
                        new
                        {
                            CompanyId = 33,
                            CompanyName = "Financial Co. 4"
                        },
                        new
                        {
                            CompanyId = 34,
                            CompanyName = "Security Co. 1"
                        },
                        new
                        {
                            CompanyId = 35,
                            CompanyName = "Security Co. 2"
                        },
                        new
                        {
                            CompanyId = 36,
                            CompanyName = "Security Co. 3"
                        },
                        new
                        {
                            CompanyId = 37,
                            CompanyName = "Security Co. 4"
                        },
                        new
                        {
                            CompanyId = 38,
                            CompanyName = "Environmental Co. 1"
                        },
                        new
                        {
                            CompanyId = 39,
                            CompanyName = "Environmental Co. 2"
                        },
                        new
                        {
                            CompanyId = 40,
                            CompanyName = "Design Co. 1"
                        },
                        new
                        {
                            CompanyId = 41,
                            CompanyName = "Design Co. 2"
                        },
                        new
                        {
                            CompanyId = 42,
                            CompanyName = "Agriculture Co. 1"
                        },
                        new
                        {
                            CompanyId = 43,
                            CompanyName = "Agriculture Co. 2"
                        },
                        new
                        {
                            CompanyId = 44,
                            CompanyName = "Agriculture Co. 3"
                        },
                        new
                        {
                            CompanyId = 45,
                            CompanyName = "Telecommunications Co. 1"
                        },
                        new
                        {
                            CompanyId = 46,
                            CompanyName = "Telecommunications Co. 2"
                        },
                        new
                        {
                            CompanyId = 47,
                            CompanyName = "Telecommunications Co. 3"
                        },
                        new
                        {
                            CompanyId = 48,
                            CompanyName = "Food Co. 1"
                        },
                        new
                        {
                            CompanyId = 49,
                            CompanyName = "Food Co. 2"
                        },
                        new
                        {
                            CompanyId = 50,
                            CompanyName = "Transport Co. 1"
                        },
                        new
                        {
                            CompanyId = 51,
                            CompanyName = "Transport Co. 2"
                        },
                        new
                        {
                            CompanyId = 52,
                            CompanyName = "Real Co. 1"
                        },
                        new
                        {
                            CompanyId = 53,
                            CompanyName = "Real Co. 2"
                        },
                        new
                        {
                            CompanyId = 54,
                            CompanyName = "Real Co. 3"
                        },
                        new
                        {
                            CompanyId = 55,
                            CompanyName = "Real Co. 4"
                        },
                        new
                        {
                            CompanyId = 56,
                            CompanyName = "Legal Co. 1"
                        },
                        new
                        {
                            CompanyId = 57,
                            CompanyName = "Legal Co. 2"
                        });
                });

            modelBuilder.Entity("TenderTask.DataAccess.Models.Tender", b =>
                {
                    b.Property<int>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenderId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetailsLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TenderId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tenders");

                    b.HasData(
                        new
                        {
                            TenderId = 1,
                            CategoryId = 1,
                            CompanyId = 1,
                            Date = new DateTime(2025, 5, 3, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(810),
                            Description = "Oil & Gas Tender 1 for Oil Co. 1",
                            DetailsLink = "https://example.com/tenders/1",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 2,
                            CategoryId = 1,
                            CompanyId = 2,
                            Date = new DateTime(2025, 5, 13, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(819),
                            Description = "Oil & Gas Tender 1 for Oil Co. 2",
                            DetailsLink = "https://example.com/tenders/2",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 3,
                            CategoryId = 1,
                            CompanyId = 2,
                            Date = new DateTime(2025, 5, 18, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(821),
                            Description = "Oil & Gas Tender 2 for Oil Co. 2",
                            DetailsLink = "https://example.com/tenders/3",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 4,
                            CategoryId = 1,
                            CompanyId = 3,
                            Date = new DateTime(2025, 5, 20, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(823),
                            Description = "Oil & Gas Tender 1 for Oil Co. 3",
                            DetailsLink = "https://example.com/tenders/4",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 5,
                            CategoryId = 1,
                            CompanyId = 3,
                            Date = new DateTime(2025, 5, 23, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(824),
                            Description = "Oil & Gas Tender 2 for Oil Co. 3",
                            DetailsLink = "https://example.com/tenders/5",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 6,
                            CategoryId = 1,
                            CompanyId = 3,
                            Date = new DateTime(2025, 5, 26, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(825),
                            Description = "Oil & Gas Tender 3 for Oil Co. 3",
                            DetailsLink = "https://example.com/tenders/6",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 7,
                            CategoryId = 2,
                            CompanyId = 4,
                            Date = new DateTime(2025, 5, 27, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(827),
                            Description = "Construction Tender 1 for Build Co. 1",
                            DetailsLink = "https://example.com/tenders/7",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 8,
                            CategoryId = 2,
                            CompanyId = 4,
                            Date = new DateTime(2025, 5, 28, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(828),
                            Description = "Construction Tender 2 for Build Co. 1",
                            DetailsLink = "https://example.com/tenders/8",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 9,
                            CategoryId = 2,
                            CompanyId = 5,
                            Date = new DateTime(2025, 5, 29, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(829),
                            Description = "Construction Tender 1 for Build Co. 2",
                            DetailsLink = "https://example.com/tenders/9",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 10,
                            CategoryId = 2,
                            CompanyId = 5,
                            Date = new DateTime(2025, 5, 30, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(830),
                            Description = "Construction Tender 2 for Build Co. 2",
                            DetailsLink = "https://example.com/tenders/10",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 11,
                            CategoryId = 3,
                            CompanyId = 6,
                            Date = new DateTime(2025, 5, 31, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(832),
                            Description = "IT Tender 1 for Tech Co. 1",
                            DetailsLink = "https://example.com/tenders/11",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 12,
                            CategoryId = 3,
                            CompanyId = 6,
                            Date = new DateTime(2025, 6, 1, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(833),
                            Description = "IT Tender 2 for Tech Co. 1",
                            DetailsLink = "https://example.com/tenders/12",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 13,
                            CategoryId = 3,
                            CompanyId = 7,
                            Date = new DateTime(2025, 6, 2, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(834),
                            Description = "IT Tender 1 for Tech Co. 2",
                            DetailsLink = "https://example.com/tenders/13",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 14,
                            CategoryId = 3,
                            CompanyId = 7,
                            Date = new DateTime(2025, 6, 3, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(835),
                            Description = "IT Tender 2 for Tech Co. 2",
                            DetailsLink = "https://example.com/tenders/14",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 15,
                            CategoryId = 4,
                            CompanyId = 8,
                            Date = new DateTime(2025, 6, 4, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(837),
                            Description = "Medical Tender 1 for Health Co. 1",
                            DetailsLink = "https://example.com/tenders/15",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 16,
                            CategoryId = 4,
                            CompanyId = 8,
                            Date = new DateTime(2025, 6, 5, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(838),
                            Description = "Medical Tender 2 for Health Co. 1",
                            DetailsLink = "https://example.com/tenders/16",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 17,
                            CategoryId = 4,
                            CompanyId = 9,
                            Date = new DateTime(2025, 6, 6, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(839),
                            Description = "Medical Tender 1 for Health Co. 2",
                            DetailsLink = "https://example.com/tenders/17",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 18,
                            CategoryId = 4,
                            CompanyId = 9,
                            Date = new DateTime(2025, 6, 7, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(841),
                            Description = "Medical Tender 2 for Health Co. 2",
                            DetailsLink = "https://example.com/tenders/18",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 19,
                            CategoryId = 5,
                            CompanyId = 10,
                            Date = new DateTime(2025, 6, 8, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(842),
                            Description = "Education Tender 1 for Edu Co. 1",
                            DetailsLink = "https://example.com/tenders/19",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 20,
                            CategoryId = 5,
                            CompanyId = 10,
                            Date = new DateTime(2025, 6, 9, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(843),
                            Description = "Education Tender 2 for Edu Co. 1",
                            DetailsLink = "https://example.com/tenders/20",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 21,
                            CategoryId = 5,
                            CompanyId = 10,
                            Date = new DateTime(2025, 6, 10, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(844),
                            Description = "Education Tender 3 for Edu Co. 1",
                            DetailsLink = "https://example.com/tenders/21",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 22,
                            CategoryId = 5,
                            CompanyId = 11,
                            Date = new DateTime(2025, 6, 11, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(846),
                            Description = "Education Tender 1 for Edu Co. 2",
                            DetailsLink = "https://example.com/tenders/22",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 23,
                            CategoryId = 5,
                            CompanyId = 11,
                            Date = new DateTime(2025, 6, 12, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(847),
                            Description = "Education Tender 2 for Edu Co. 2",
                            DetailsLink = "https://example.com/tenders/23",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 24,
                            CategoryId = 6,
                            CompanyId = 12,
                            Date = new DateTime(2025, 6, 13, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(848),
                            Description = "Agriculture Tender 1 for Agro Co. 1",
                            DetailsLink = "https://example.com/tenders/24",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 25,
                            CategoryId = 6,
                            CompanyId = 12,
                            Date = new DateTime(2025, 6, 14, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(849),
                            Description = "Agriculture Tender 2 for Agro Co. 1",
                            DetailsLink = "https://example.com/tenders/25",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 26,
                            CategoryId = 6,
                            CompanyId = 13,
                            Date = new DateTime(2025, 6, 15, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(851),
                            Description = "Agriculture Tender 1 for Agro Co. 2",
                            DetailsLink = "https://example.com/tenders/26",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 27,
                            CategoryId = 6,
                            CompanyId = 13,
                            Date = new DateTime(2025, 6, 16, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(852),
                            Description = "Agriculture Tender 2 for Agro Co. 2",
                            DetailsLink = "https://example.com/tenders/27",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 28,
                            CategoryId = 7,
                            CompanyId = 14,
                            Date = new DateTime(2025, 6, 17, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(853),
                            Description = "Transport Tender 1 for Trans Co. 1",
                            DetailsLink = "https://example.com/tenders/28",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 29,
                            CategoryId = 7,
                            CompanyId = 14,
                            Date = new DateTime(2025, 6, 18, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(855),
                            Description = "Transport Tender 2 for Trans Co. 1",
                            DetailsLink = "https://example.com/tenders/29",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 30,
                            CategoryId = 7,
                            CompanyId = 15,
                            Date = new DateTime(2025, 6, 19, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(856),
                            Description = "Transport Tender 1 for Trans Co. 2",
                            DetailsLink = "https://example.com/tenders/30",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 31,
                            CategoryId = 7,
                            CompanyId = 15,
                            Date = new DateTime(2025, 6, 20, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(857),
                            Description = "Transport Tender 2 for Trans Co. 2",
                            DetailsLink = "https://example.com/tenders/31",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 32,
                            CategoryId = 8,
                            CompanyId = 16,
                            Date = new DateTime(2025, 6, 21, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(858),
                            Description = "Energy Tender 1 for Energy Co. 1",
                            DetailsLink = "https://example.com/tenders/32",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 33,
                            CategoryId = 8,
                            CompanyId = 16,
                            Date = new DateTime(2025, 6, 22, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(860),
                            Description = "Energy Tender 2 for Energy Co. 1",
                            DetailsLink = "https://example.com/tenders/33",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 34,
                            CategoryId = 8,
                            CompanyId = 17,
                            Date = new DateTime(2025, 6, 23, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(861),
                            Description = "Energy Tender 1 for Energy Co. 2",
                            DetailsLink = "https://example.com/tenders/34",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 35,
                            CategoryId = 8,
                            CompanyId = 17,
                            Date = new DateTime(2025, 6, 24, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(862),
                            Description = "Energy Tender 2 for Energy Co. 2",
                            DetailsLink = "https://example.com/tenders/35",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 36,
                            CategoryId = 9,
                            CompanyId = 18,
                            Date = new DateTime(2025, 6, 25, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(863),
                            Description = "Finance Tender 1 for Finance Co. 1",
                            DetailsLink = "https://example.com/tenders/36",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 37,
                            CategoryId = 9,
                            CompanyId = 18,
                            Date = new DateTime(2025, 6, 26, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(865),
                            Description = "Finance Tender 2 for Finance Co. 1",
                            DetailsLink = "https://example.com/tenders/37",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 38,
                            CategoryId = 9,
                            CompanyId = 19,
                            Date = new DateTime(2025, 6, 27, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(866),
                            Description = "Finance Tender 1 for Finance Co. 2",
                            DetailsLink = "https://example.com/tenders/38",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 39,
                            CategoryId = 9,
                            CompanyId = 19,
                            Date = new DateTime(2025, 6, 28, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(867),
                            Description = "Finance Tender 2 for Finance Co. 2",
                            DetailsLink = "https://example.com/tenders/39",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 40,
                            CategoryId = 10,
                            CompanyId = 20,
                            Date = new DateTime(2025, 6, 29, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(868),
                            Description = "Legal Tender 1 for Legal Co. 1",
                            DetailsLink = "https://example.com/tenders/40",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 41,
                            CategoryId = 10,
                            CompanyId = 20,
                            Date = new DateTime(2025, 6, 30, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(870),
                            Description = "Legal Tender 2 for Legal Co. 1",
                            DetailsLink = "https://example.com/tenders/41",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 42,
                            CategoryId = 10,
                            CompanyId = 21,
                            Date = new DateTime(2025, 7, 1, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(871),
                            Description = "Legal Tender 1 for Legal Co. 2",
                            DetailsLink = "https://example.com/tenders/42",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 43,
                            CategoryId = 10,
                            CompanyId = 21,
                            Date = new DateTime(2025, 7, 2, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(872),
                            Description = "Legal Tender 2 for Legal Co. 2",
                            DetailsLink = "https://example.com/tenders/43",
                            Status = 0
                        },
                        new
                        {
                            TenderId = 44,
                            CategoryId = 11,
                            CompanyId = 22,
                            Date = new DateTime(2025, 7, 3, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(874),
                            Description = "Telecom Tender 1 for Telecom Co. 1",
                            DetailsLink = "https://example.com/tenders/44",
                            Status = 1
                        },
                        new
                        {
                            TenderId = 45,
                            CategoryId = 11,
                            CompanyId = 22,
                            Date = new DateTime(2025, 7, 4, 18, 59, 24, 453, DateTimeKind.Utc).AddTicks(875),
                            Description = "Telecom Tender 2 for Telecom Co. 1",
                            DetailsLink = "https://example.com/tenders/45",
                            Status = 0
                        });
                });

            modelBuilder.Entity("TenderTask.DataAccess.Models.Tender", b =>
                {
                    b.HasOne("TenderTask.DataAccess.Models.Category", "Category")
                        .WithMany("Tenders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenderTask.DataAccess.Models.Company", "Company")
                        .WithMany("Tenders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TenderTask.DataAccess.Models.Category", b =>
                {
                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("TenderTask.DataAccess.Models.Company", b =>
                {
                    b.Navigation("Tenders");
                });
#pragma warning restore 612, 618
        }
    }
}
